import type { Metadata } from "next";
import { Figtree } from "next/font/google"; 
import "./globals.css";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree", 
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${figtree.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}